[package]
name = "tezos_api"
version = "0.9.0"
authors = ["Tomas Sedlak <tomas.sedlak@simplestaking.com>"]
edition = "2018"

[dependencies]
derive_builder = "0.9"
enum-iterator = "0.6"
failure = "0.1"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.4"
ocaml-interop = { git = "https://github.com/simplestaking/ocaml-interop.git", branch = "runtime-handle", features = ["docs-rs"] }
serde = { version = "1.0", features = ["derive"] }
# local dependencies
crypto = { path = "../../crypto" }
tezos_messages = { path = "../messages" }

[dev-dependencies]
hex = "0.4"